services:
  - type: web
    name: laxmi-education
    env: node
    rootDir: .
    buildCommand: yarn install --frozen-lockfile && yarn build
    startCommand: yarn start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
